### ISSUE TITLE
horrivel faz de novo

### ISSUE THREAD

**Issue by YuriMSdS** [leonelpucineli/Notes#4]
Após um intenso code review pude concluir o estado atual do código e a ação necessária:

•estado
 >Horrível

•ação necessária
 > Fazer de novo

**Comment by leonelpucineli** [comment]
compreensivel senhor bunda, tenha um otimo dia

**Comment by leonelpucineli** [comment]
quem concordar com o yuri é guei

**Comment by YuriMSdS** [comment]
quem discordar é mais ainda

**Comment by leonelpucineli** [comment]
everybody is gay

**Comment by YuriMSdS** [comment]
eu nao, minha mae n deixa
